### ISSUE TITLE
使用webstack-hugo主题是必须授权后才能使用？

### ISSUE THREAD

**Issue by liu-yanbo** [tznb1/TwoNav#1]
使用webstack-hugo主题是必须授权后才能使用？

**Comment by tznb1** [comment]
您好,使用主题不需要授权的! 但使用在线下载功能需要授权!

**Comment by keaiye** [comment]
没买授权限制太多，网站名都不能改，还是继续用onenav吧

**Comment by tznb1** [comment]
> 没买授权限制太多，网站标题都不能改，还是继续用onenav吧

TwoNav是多用户使用...
没授权的你只是不能改<默认设置>中的<站点标题>...
但你可以改<站点设置>中的标题
何为默认设置? 页面中也说明了: 2.用户注册后默认使用此方案
即使您是授权用户..你修改此处也不会生效,
因为它只针对用户注册默认的配置..并不会去修改现有用户的配置
而站点设置是针对当前账号的 ..(无需授权)
你可以继续使用onenav..
但请不要在没搞清楚时就乱说话...

**Comment by keaiye** [comment]
> > 没买授权限制太多，网站标题都不能改，还是继续用onenav吧
> 
> TwoNav是多用户使用... 没授权的你只是不能改<默认设置>中的<站点标题>... 但你可以改<站点设置>中的标题 何为默认设置? 页面中也说明了: 2.用户注册后默认使用此方案 即使您是授权用户..你修改此处也不会生效, 因为它只针对用户注册默认的配置..并不会去修改现有用户的配置 而站点设置是针对当前账号的 ..(无需授权) 你可以继续使用onenav.. 但请不要在没搞清楚时就乱说话...

行吧，是我理解错了，向您道歉
