### ISSUE TITLE
你好，请问下是否支持英文版本呢

### ISSUE THREAD

**Issue by mrseawood** [tznb1/TwoNav#5]
因为有做英文站的需求，所以请问下后台设置中是否有修改成英文界面的选项呢。
我在后台查找了一番，并没有找到修改成英文界面的选项。

**Comment by tznb1** [comment]
你好,不支持修改成英文

**Comment by mrseawood** [comment]
请问后续会考虑添加上吗
谢谢

**Comment by tznb1** [comment]
不考虑支持多语言
因为设计之处就没计划支持多语言
现在去支持的话工作量太大了

**Comment by mrseawood** [comment]
好的 谢谢你的回复
辛苦辛苦了
