### ISSUE TITLE
兼容OneNav的数据吗，或者有没有简单的方法把OneNav的数据导过来

### ISSUE THREAD

**Issue by liesauer** [tznb1/TwoNav#6]
RT

**Comment by tznb1** [comment]
导入OneNav书签 
方法1
登录您的服务器或空间 使用Web/FTP/SSH均可
找到OneNav的安装目录 > 打开data目录 > 找到onenav.db3文件 > 将其下载到电脑
登录TwoNav后台 > 导出导入 > 上传刚下载的onenav.db3文件
方法2
登录OneNav后台 > 我的链接 > 导出所有链接(列表左下角)
登录TwoNav后台 > 导出导入 > 上传刚导出的HTML文件
方法3 (需订阅)
登录OneNav后台 > 数据备份 > 立即备份 > 下载刚备份的数据
登录TwoNav后台 > 导出导入 > 上传刚下载的db3文件

**Comment by liesauer** [comment]
好的，感谢
