### ISSUE TITLE
安装引导页面提示保存配置失败

### ISSUE THREAD

**Issue by FannyCheung** [tznb1/TwoNav#7]
腾讯云服务器 mysql5.7，网页能打开，但安装不了，提示“保存配置失败”

**Comment by tznb1** [comment]
跟数据库无关, 是站点目录权限的问题 安装程序在将配置写到data目录下时无法写入导致的 检测读写权限

**Comment by FannyCheung** [comment]
是的，主目录和里面文件的所有者、组不同，改成一样的www就能正常使用了，感谢~
